"""Initial schema with memory assistant models

Revision ID: dfe82a32a657
Revises: 
Create Date: 2026-08-12 18:04:34.368083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfe82a32a657'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('feedback')
    op.drop_table('pull_requests')
    op.drop_table('installations')
    op.drop_table('findings')
    op.create_index(op.f('ix_event_nodes_person_id'), 'event_nodes', ['person_id'], unique=False)
    op.create_index(op.f('ix_event_nodes_work_item_id'), 'event_nodes', ['work_item_id'], unique=False)
    op.create_foreign_key(None, 'event_nodes', 'work_items', ['work_item_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'event_nodes', 'persons', ['person_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_knowledge_nodes_event_id'), 'knowledge_nodes', ['event_id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_source'), 'knowledge_nodes', ['source'], unique=False)
    op.add_column('repositories', sa.Column('github_installation_id', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('github_repository_id', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('repositories', sa.Column('full_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_repositories_github_installation_id'), 'repositories', ['github_installation_id'], unique=False)
    op.create_foreign_key(None, 'repositories', 'github_installations', ['github_installation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_index(op.f('ix_repositories_github_installation_id'), table_name='repositories')
    op.drop_column('repositories', 'full_name')
    op.drop_column('repositories', 'owner')
    op.drop_column('repositories', 'github_repository_id')
    op.drop_column('repositories', 'github_installation_id')
    op.drop_index(op.f('ix_knowledge_nodes_source'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_event_id'), table_name='knowledge_nodes')
    op.drop_constraint(None, 'event_nodes', type_='foreignkey')
    op.drop_constraint(None, 'event_nodes', type_='foreignkey')
    op.drop_index(op.f('ix_event_nodes_work_item_id'), table_name='event_nodes')
    op.drop_index(op.f('ix_event_nodes_person_id'), table_name='event_nodes')
    op.create_table('findings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('pull_request_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('github_comment_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'open'::text"), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suggestion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('findings_pkey'))
    )
    op.create_table('installations',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('account_login', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('account_type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sender_login', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('installations_pkey'))
    )
    op.create_table('pull_requests',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('repository_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('github_pr_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('pr_number', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pull_requests_pkey'))
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('finding_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('github_user', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reaction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meaning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('feedback_pkey'))
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('installation_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('repository_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    # ### end Alembic commands ###
