from typing import Optional, List, Dict, Any
from src.ai.llm_service import llm_service
from src.ai.embedding_service import embedding_service
from src.services.diff_filter_service import diff_filter_service


class ChangeAnalyzerService:

    def generate_pr_comment_markdown(self, change_record: Dict[str, Any]) -> str:
        """
        Generates the human-readable Markdown comment from the structured change record.
        """
        summary = change_record.get("summary", "No summary available.")
        changes = change_record.get("changes", [])
        impact = change_record.get("impact", [])

        lines = [
            "###  Tzylo Change Summary",
            "",
            f"**Summary:** {summary}",
            "",
            "#### Changes"
        ]

        if changes:
            for item in changes:
                if isinstance(item, dict):
                    area = item.get("area") or "General"
                    desc = item.get("description") or ""
                    lines.append(f"- **{area}**: {desc}")
                elif isinstance(item, str):
                    lines.append(f"- {item}")
        else:
            lines.append("- General maintenance and updates.")

        if impact:
            lines.append("")
            lines.append("#### Impact")
            for imp in impact:
                lines.append(f"- {imp}")

        lines.append("")
        lines.append("---")
        lines.append("*Generated by [Tzylo](https://tzylo.com)*")

        return "\n".join(lines)

    async def analyze_pr(
        self,
        title: str,
        body: str,
        files_data: Optional[List[Dict[str, Any]]] = None,
        changed_files: Optional[List[str]] = None,
        diff_snippet: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Takes PR metadata and changed files/patches.
        1. Passes through DiffFilterService to filter noise & truncate to budget.
        2. Queries LLM for strictly structured JSON ChangeRecord.
        3. Generates human-readable PR comment markdown.
        4. Computes text representation and vector embedding for RAG.
        """
        # 1. Filter Diff
        if files_data:
            formatted_diff, filtered_files, filter_stats = diff_filter_service.filter_and_format_diff(files_data)
        else:
            raw_files = [{"filename": f, "patch": diff_snippet if i == 0 else ""} for i, f in enumerate(changed_files or [])]
            formatted_diff, filtered_files, filter_stats = diff_filter_service.filter_and_format_diff(raw_files)

        if not formatted_diff and diff_snippet:
            formatted_diff = diff_snippet[:diff_filter_service.max_total_diff_chars]

        # 2. Extract structured change record via LLM
        structured_record = await llm_service.analyze_pr_change(
            pr_title=title,
            pr_body=body,
            changed_files=filtered_files,
            diff_snippet=formatted_diff
        )

        summary = structured_record.get("summary", title)
        changes = structured_record.get("changes", [])
        impact = structured_record.get("impact", [])
        files_changed = structured_record.get("files_changed", filtered_files)

        # 3. Generate human-readable comment
        comment_markdown = self.generate_pr_comment_markdown(structured_record)

        # 4. Construct canonical representation for vector RAG embedding
        change_descriptions = []
        for c in changes:
            if isinstance(c, dict):
                change_descriptions.append(f"{c.get('area', '')}: {c.get('description', '')}")
            else:
                change_descriptions.append(str(c))

        text_to_embed = (
            f"PR Title: {title}. Summary: {summary}. "
            f"Changes: {'; '.join(change_descriptions)}. "
            f"Impact: {'; '.join(impact)}."
        )

        try:
            embedding = await embedding_service.embed(text_to_embed)
        except Exception as e:
            print(f"[EMBEDDING ERROR] Failed to embed change record: {e}")
            embedding = None

        return {
            "summary": summary,
            "changes": changes,
            "impact": impact,
            "files_changed": files_changed,
            "comment_markdown": comment_markdown,
            "text_representation": text_to_embed,
            "embedding": embedding,
            "filter_stats": filter_stats
        }


change_analyzer_service = ChangeAnalyzerService()
